#pessoa = input("digite o nome da pessoa:")
#print("Boa noite",pessoa)
#idade = input("Qual a sua idade? ")
#print("Nossa!Você já tem ",idade,"anos")
#email = input("Digite seu e-mail: ")
#print(email,",e-mail salvo.")
numero = input("Digite um número: ")
outronumero = input("Digite outro número: ")
print("A soma desses números é igual a: ",float(numero) + float(outronumero))